add all links for Newsmax, ran into error when there was only 1 item from a particular xml page it throws 'TypeError: data[Symbol.iterator] is not a function' error. need to fix this